from .api import compose_series, generate_dataset, generate_series
from .datasets import SeriesDataset, TaskDataset, TaskSpec, generate_series_dataset, taskify_dataset
from .compiler import Compiler
from .series import GeneratedSeries
from .specs import ObservationSpec, SeriesSpec
from .trace import SeriesTrace

from .analysis.describe import SeriesDescription, describe_series, infer_structure_tags, suggest_spec
from .analysis.dataset import DatasetDescription, describe_dataset
from .analysis.explain import SeriesExplanation, explain_series
from .report.eda import (
    EDAReport,
    generate_eda_report,
    generate_dataset_eda_report,
    generate_linked_eda_bundle,
    generate_linked_dataset_eda_bundle,
)
from .integrations.external import ExternalRollout, wrap_external_series
from .integrations.live import fetch_coingecko_market_chart, fetch_fred_series, fetch_github_stars_series
from .similarity import SimilarityMatrix, SimilarityResult, compare_series, explain_similarity, find_top_matches, pairwise_similarity
from .counterfactual import CounterfactualPair, generate_counterfactual_pair, with_intervention, with_policy
from .interventions import InterventionSpec
from .policies import ConstantPolicy, LinearFeedbackPolicy, PiecewiseConstantPolicy, ThresholdPolicy
from .agent import (
    ActionPlanItem,
    AgentContextPack,
    ArtifactCard,
    DatasetHandoffBundle,
    HandoffArtifact,
    HandoffIndex,
    build_dataset_handoff_bundle,
    render_dataset_handoff_markdown,
    render_handoff_index_markdown,
    save_dataset_handoff_bundle,
    DocsSiteResult,
    FAQEntry,
    FAQ_ENTRIES,
    EDARoute,
    EDAResourceHub,
    EDAResourceLink,
    EDATaskSuggestion,
    common_eda_finding_routes,
    build_eda_resource_hub,
    render_eda_resource_hub_markdown,
    save_eda_resource_hub,
    build_agent_context,
    build_dataset_context,
    build_series_context,
    build_series_dataset_card,
    build_task_context,
    build_task_dataset_card,
    example_catalog,
    examples_by_category,
    TutorialTrack,
    EnvironmentProfile,
    ScenarioProfile,
    Playbook,
    StarterKit,
    NotebookAsset,
    StarterProjectResult,
    tutorial_catalog,
    playbook_catalog,
    starter_catalog,
    environment_catalog,
    scenario_catalog,
    recommend_tutorials,
    recommend_playbooks,
    recommend_starters,
    recommend_scenarios,
    recommend_environments,
    generate_docs_site,
    create_starter_project,
    export_tutorial_notebooks,
    recommend_examples,
    render_context_markdown,
    APIReference,
    APICategory,
    APISymbol,
    PackageProfile,
    PositioningMatrix,
    competitor_catalog,
    build_positioning_matrix,
    render_positioning_markdown,
    save_positioning_matrix,
    recommend_companions,
    build_api_reference,
    render_api_reference_markdown,
    save_api_reference,
)

from .demo_assets import DemoScenario, build_demo_dataset, demo_scenario_catalog

from .surface import (
    PublicEntrypoint,
    PublicSurface,
    demo,
    handoff,
    launch_gui,
    load_asset,
    public_surface,
    render_public_surface_markdown,
    report,
    save_public_surface,
    taskify,
)
from .agent.schemas import (
    ArtifactSchema,
    ArtifactSchemaCatalog,
    build_artifact_schemas,
    save_artifact_schemas,
)
from .agent.tool_contracts import (
    ToolContract,
    ToolContractCatalog,
    build_tool_contracts,
    save_tool_contracts,
)

# Import registrable modules so deserialization works out of the box.
from .dynamics.control import EventTriggeredController, SecondOrderTracking
from .dynamics.causal import CausalTreatmentOutcome, CausalVARX
from .dynamics.policy import PolicyControlledStateSpace
from .dynamics.regime import RegimeSwitch
from .dynamics.state_space import JointServoMIMO, LinearStateSpace
from .observation import (
    BlockMissing,
    Clamp,
    Downsample,
    IrregularSampling,
    MeasurementNoise,
    RegularSampling,
)
from .operators import Add, Convolve, Multiply, TimeWarp
from .operators import Stack
from .primitives.control import PiecewiseConstantInput, SineInput, StepReference, WaypointTrajectory
from .primitives.events import BurstyPulseTrain
from .primitives.noise import AR1Noise, RandomWalkProcess, WhiteGaussianNoise
from .primitives.seasonal import MultiSineSeasonality, QuasiPeriodicSeasonality, SineSeasonality
from .primitives.trend import LinearTrend, PiecewiseLinearTrend

_FULL_EXPORTS = [
    "Add",
    "AgentContextPack",
    "AR1Noise",
    "ArtifactCard",
    "DatasetHandoffBundle",
    "HandoffArtifact",
    "HandoffIndex",
    "APIReference",
    "APICategory",
    "APISymbol",
    "PackageProfile",
    "PositioningMatrix",
    "competitor_catalog",
    "build_positioning_matrix",
    "render_positioning_markdown",
    "save_positioning_matrix",
    "recommend_companions",
    "BlockMissing",
    "build_agent_context",
    "build_api_reference",
    "build_dataset_context",
    "build_series_context",
    "build_series_dataset_card",
    "build_dataset_handoff_bundle",
    "build_task_context",
    "build_task_dataset_card",
    "BurstyPulseTrain",
    "CausalTreatmentOutcome",
    "CausalVARX",
    "Clamp",
    "Compiler",
    "compose_series",
    "Convolve",
    "ConstantPolicy",
    "CounterfactualPair",
    "DatasetDescription",
    "describe_dataset",
    "describe_series",
    "DocsSiteResult",
    "FAQEntry",
    "FAQ_ENTRIES",
    "DemoScenario",
    "Downsample",
    "EDAReport",
    "EDARoute",
    "EDAResourceHub",
    "EDAResourceLink",
    "EDATaskSuggestion",
    "EventTriggeredController",
    "ExternalRollout",
    "example_catalog",
    "examples_by_category",
    "TutorialTrack",
    "EnvironmentProfile",
    "ScenarioProfile",
    "Playbook",
    "StarterKit",
    "NotebookAsset",
    "StarterProjectResult",
    "playbook_catalog",
    "starter_catalog",
    "tutorial_catalog",
    "environment_catalog",
    "scenario_catalog",
    "recommend_playbooks",
    "recommend_starters",
    "recommend_tutorials",
    "recommend_scenarios",
    "recommend_environments",
    "explain_series",
    "generate_counterfactual_pair",
    "generate_dataset",
    "generate_dataset_eda_report",
    "generate_docs_site",
    "build_demo_dataset",
    "demo_scenario_catalog",
    "create_starter_project",
    "export_tutorial_notebooks",
    "generate_linked_eda_bundle",
    "generate_linked_dataset_eda_bundle",
    "generate_eda_report",
    "generate_series",
    "build_eda_resource_hub",
    "generate_series_dataset",
    "GeneratedSeries",
    "infer_structure_tags",
    "InterventionSpec",
    "IrregularSampling",
    "JointServoMIMO",
    "LinearFeedbackPolicy",
    "LinearStateSpace",
    "common_eda_finding_routes",
    "LinearTrend",
    "MeasurementNoise",
    "MultiSineSeasonality",
    "Multiply",
    "ObservationSpec",
    "PiecewiseConstantInput",
    "PiecewiseConstantPolicy",
    "PiecewiseLinearTrend",
    "PolicyControlledStateSpace",
    "QuasiPeriodicSeasonality",
    "RandomWalkProcess",
    "recommend_examples",
    "RegularSampling",
    "RegimeSwitch",
    "render_api_reference_markdown",
    "render_context_markdown",
    "render_dataset_handoff_markdown",
    "render_handoff_index_markdown",
    "SecondOrderTracking",
    "SeriesDataset",
    "SeriesDescription",
    "SeriesExplanation",
    "SeriesSpec",
    "SeriesTrace",
    "SineInput",
    "SineSeasonality",
    "Stack",
    "StepReference",
    "suggest_spec",
    "render_eda_resource_hub_markdown",
    "TaskDataset",
    "TaskSpec",
    "taskify_dataset",
    "ThresholdPolicy",
    "TimeWarp",
    "WaypointTrajectory",
    "WhiteGaussianNoise",
    "with_intervention",
    "with_policy",
    "wrap_external_series",
    "save_api_reference",
    "save_dataset_handoff_bundle",
    "save_eda_resource_hub",
    "SimilarityMatrix",
    "SimilarityResult",
    "compare_series",
    "pairwise_similarity",
    "find_top_matches",
    "explain_similarity",
    "fetch_fred_series",
    "fetch_coingecko_market_chart",
    "fetch_github_stars_series",

]

__version__ = "0.3.7"


__all__ = [
    'ArtifactSchema',
    'ArtifactSchemaCatalog',
    'DatasetHandoffBundle',
    'EDAReport',
    'PublicEntrypoint',
    'PublicSurface',
    'SeriesDataset',
    'TaskDataset',
    'build_api_reference',
    'build_artifact_schemas',
    'build_dataset_context',
    'build_dataset_handoff_bundle',
    'build_series_dataset_card',
    'demo',
    'generate_dataset_eda_report',
    'generate_docs_site',
    'generate_eda_report',
    'handoff',
    'launch_gui',
    'load_asset',
    'public_surface',
    'render_public_surface_markdown',
    'report',
    'save_api_reference',
    'save_artifact_schemas',
    'save_public_surface',
    'taskify',
]

_FULL_EXPORTS = tuple(sorted(set(_FULL_EXPORTS) | set(__all__)))
