name: Feature request
description: Suggest an improvement to TSDataForge
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
